theme: jekyll-theme-minimal 
title: Calculadora-CoeficientesDispersion
description: Este proyecto permite calcular los coeficientes de dispersión del modelo gaussiano de contaminates de manera sencilla e interactiva.
